### PR TITLE
[hd110.xml] Update remote control layout

### PR DESCRIPTION
**Pull request by IanSav**
- Improve button locations.
- Add missing button definitions.

### CODE REVIEW

**Comment by wedebe** [comment]
All buttons mapped, many thanks :)

Comments:
Not at all necessary but for pixel perfection...
`3`, `NEXT` could be moved to the right by a pixel
`PVR` down 1px, left 1px
`SLEEP`, `TV`, `Unknown [PORTAL]` left 1px

Screenshots:
Unknown PORTAL
KEY_YELLOW
KEY_VOLUMEUP
KEY_UP
KEY_VOLUMEDOWN
KEY_TV
KEY_TEXT
KEY_SUBTITLE
KEY_STOP
KEY_SLEEP
KEY_RIGHT
KEY_REWIND
KEY_RED
KEY_RECORD
KEY_RADIO
KEY_PVR
KEY_PROGRAM
KEY_PREVIOUSSONG
KEY_PLAYPAUSE
KEY_POWER
KEY_PREVIOUS
KEY_OK
KEY_NEXTSONG
KEY_NEXT
KEY_MUTE
KEY_MENU
KEY_LEFT
KEY_HELP
KEY_INFO
KEY_GREEN
KEY_EXIT
KEY_FASTFORWARD
KEY_CHANNELDOWN
KEY_EPG
KEY_DOWN
KEY_CHANNELUP
KEY_BLUE
KEY_AUDIO
KEY_9
KEY_8
KEY_6
KEY_7
KEY_2
KEY_5
KEY_3
KEY_4
KEY_0
KEY_1

**Comment by IanSav** [comment]
@wedebe there is an easier way to review all the button assignments.  Just go to https://github.com/oe-alliance/remotes/blob/previews/hd1100.png .

What code does the PORTAL button send?  Do *ALL* the other buttons do what you expect?  That is, for every button shown in the HELP screen debug screen is the "Key" value correct for that button?

When you tell me what code is sent by PORTAL I will correct that code in the XML file.  If any of the buttons are sending the wrong code please also tell me what the codes should be.

**Comment by wedebe** [comment]
`PORTAL` is called `CONTEXT` on mine, and triggers a notification to say that `The MediaPortal plugin is not installed`.

```
11:39:00.5546 [eRCDeviceInputDev] 1 9c 1
11:39:00.5553 [InfoBarGenerics] Key 'KEY_BOOKMARKS' (156) Make.
11:39:00.8692 [eRCDeviceInputDev] 0 9c 1
11:39:00.8698 [InfoBarGenerics] Key 'KEY_BOOKMARKS' (156) Break.
11:39:00.8763 [ActionMap] Map context 'InfobarActions' -> Action 'showWWW'.
11:39:00.8788 [Skin] Processing screen 'MessageBox', position=(240, 160), size=(800x400) for module 'MessageBox'.
11:39:00.8940 [Screen] Warning: Skin is missing element 'QuestionPixmap' in <class 'Screens.MessageBox.MessageBox'>(The MediaPortal plugin is not installed!
Please install it.).11:39:00.8942 
11:39:00.8945 [Screen] Warning: Skin is missing element 'InfoPixmap' in <class 'Screens.MessageBox.MessageBox'>(The MediaPortal plugin is not installed!
Please install it.).11:39:00.8946 
11:39:00.8949 [Screen] Warning: Skin is missing element 'ErrorPixmap' in <class 'Screens.MessageBox.MessageBox'>(The MediaPortal plugin is not installed!
Please install it.).11:39:00.8949 
11:39:00.8955 [MessageBox] Timeout set to 10 seconds.
11:39:00.8982 [Skin] Processing screen 'MessageBoxSummary' from list 'MessageBoxSummary, ScreenSummary, MessageBox_summary, SimpleSummary', position=(0, 0), size=(132x64) for module 'MessageBoxSummary'.
11:39:00.8999 [Screen] Showing screen '['MessageBoxSummary', 'ScreenSummary', 'MessageBox_summary', 'SimpleSummary']'.
11:39:00.9005 [Screen] Showing screen '['MessageBox']'.
```

**Comment by wedebe** [comment]
All buttons performing as expected :)

Here's the log for each button pressed (mostly*) in top-left to bottom-right row order.
*Up and Down may be out of sequence per remote; OK is pressed last.

```
11:41:50.1561 [eRCDeviceInputDev] 1 74 1
11:41:50.1565 [InfoBarGenerics] Key 'KEY_POWER' (116) Make.
11:41:50.1568 [ActionMap] Map context 'GlobalActions' -> Action 'power_down'.
11:41:50.3571 [eRCDeviceInputDev] 0 74 1
11:41:50.3575 [InfoBarGenerics] Key 'KEY_POWER' (116) Break.
11:41:50.3578 [ActionMap] Map context 'GlobalActions' -> Action 'power_up'.
11:41:51.1521 [eRCDeviceInputDev] 1 71 1
11:41:51.1525 [InfoBarGenerics] Key 'KEY_MUTE' (113) Make.
11:41:51.1529 [ActionMap] Map context 'GlobalActions' -> Action 'volumeMute'.
11:41:51.1576 [Screen] Showing screen 'Mute'.
11:41:51.1582 [Volume] Volume set to 0.
11:41:51.3571 [eRCDeviceInputDev] 0 71 1
11:41:51.3576 [InfoBarGenerics] Key 'KEY_MUTE' (113) Break.
11:41:53.0934 [eRCDeviceInputDev] 1 8e 1
11:41:53.0940 [InfoBarGenerics] Key 'KEY_SLEEP' (142) Make.
11:41:53.3013 [eRCDeviceInputDev] 0 8e 1
11:41:53.3018 [InfoBarGenerics] Key 'KEY_SLEEP' (142) Break.
11:41:54.2195 [eRCDeviceInputDev] 1 179 1
11:41:54.2201 [InfoBarGenerics] Key 'KEY_TV' (377) Make.
11:41:54.4211 [eRCDeviceInputDev] 0 179 1
11:41:54.4216 [InfoBarGenerics] Key 'KEY_TV' (377) Break.
11:41:55.1730 [eRCDeviceInputDev] 1 181 1
11:41:55.1737 [InfoBarGenerics] Key 'KEY_RADIO' (385) Make.
11:41:55.3812 [eRCDeviceInputDev] 0 181 1
11:41:55.3817 [InfoBarGenerics] Key 'KEY_RADIO' (385) Break.
11:41:56.0972 [eRCDeviceInputDev] 1 8a 1
11:41:56.0978 [InfoBarGenerics] Key 'KEY_HELP' (138) Make.
11:41:56.3012 [eRCDeviceInputDev] 0 8a 1
11:41:56.3016 [InfoBarGenerics] Key 'KEY_HELP' (138) Break.
11:41:56.3020 [ActionMap] Map context 'HelpActions' -> Action 'displayHelp'.

11:41:57.9002 [eRCDeviceInputDev] 1 188 1
11:41:57.9008 [InfoBarGenerics] Key 'KEY_AUDIO' (392) Make.
11:41:58.2132 [eRCDeviceInputDev] 0 188 1
11:41:58.2137 [InfoBarGenerics] Key 'KEY_AUDIO' (392) Break.
11:41:58.9642 [eRCDeviceInputDev] 1 172 1
11:41:58.9648 [InfoBarGenerics] Key 'KEY_SUBTITLE' (370) Make.
11:41:59.2772 [eRCDeviceInputDev] 0 172 1
11:41:59.2777 [InfoBarGenerics] Key 'KEY_SUBTITLE' (370) Break.
11:41:59.9005 [eRCDeviceInputDev] 1 184 1
11:41:59.9011 [InfoBarGenerics] Key 'KEY_TEXT' (388) Make.
11:42:00.1092 [eRCDeviceInputDev] 0 184 1
11:42:00.1095 [InfoBarGenerics] Key 'KEY_TEXT' (388) Break.
11:42:01.8541 [eRCDeviceInputDev] 1 2 1
11:42:01.8547 [InfoBarGenerics] Key 'KEY_1' (2) Make.
11:42:02.0611 [eRCDeviceInputDev] 0 2 1
11:42:02.0616 [InfoBarGenerics] Key 'KEY_1' (2) Break.
11:42:02.7015 [eRCDeviceInputDev] 1 3 1
11:42:02.7020 [InfoBarGenerics] Key 'KEY_2' (3) Make.
11:42:02.9092 [eRCDeviceInputDev] 0 3 1
11:42:02.9095 [InfoBarGenerics] Key 'KEY_2' (3) Break.
11:42:03.4860 [eRCDeviceInputDev] 1 4 1
11:42:03.4865 [InfoBarGenerics] Key 'KEY_3' (4) Make.
11:42:03.7972 [eRCDeviceInputDev] 0 4 1
11:42:03.7975 [InfoBarGenerics] Key 'KEY_3' (4) Break.
11:42:04.6034 [eRCDeviceInputDev] 1 5 1
11:42:04.6037 [InfoBarGenerics] Key 'KEY_4' (5) Make.
11:42:04.8052 [eRCDeviceInputDev] 0 5 1
11:42:04.8055 [InfoBarGenerics] Key 'KEY_4' (5) Break.
11:42:05.3075 [eRCDeviceInputDev] 1 6 1
11:42:05.3079 [InfoBarGenerics] Key 'KEY_5' (6) Make.
11:42:05.5091 [eRCDeviceInputDev] 0 6 1
11:42:05.5094 [InfoBarGenerics] Key 'KEY_5' (6) Break.
11:42:05.9010 [eRCDeviceInputDev] 1 7 1
11:42:05.9016 [InfoBarGenerics] Key 'KEY_6' (7) Make.
11:42:06.1092 [eRCDeviceInputDev] 0 7 1
11:42:06.1096 [InfoBarGenerics] Key 'KEY_6' (7) Break.
11:42:07.0341 [eRCDeviceInputDev] 1 8 1
11:42:07.0348 [InfoBarGenerics] Key 'KEY_7' (8) Make.
11:42:07.2372 [eRCDeviceInputDev] 0 8 1
11:42:07.2377 [InfoBarGenerics] Key 'KEY_7' (8) Break.
11:42:07.6023 [eRCDeviceInputDev] 1 9 1
11:42:07.6028 [InfoBarGenerics] Key 'KEY_8' (9) Make.
11:42:07.8051 [eRCDeviceInputDev] 0 9 1
11:42:07.8055 [InfoBarGenerics] Key 'KEY_8' (9) Break.
11:42:08.2945 [eRCDeviceInputDev] 1 a 1
11:42:08.2948 [InfoBarGenerics] Key 'KEY_9' (10) Make.
11:42:08.5012 [eRCDeviceInputDev] 0 a 1
11:42:08.5016 [InfoBarGenerics] Key 'KEY_9' (10) Break.
11:42:10.1050 [eRCDeviceInputDev] 1 19c 1
11:42:10.1053 [InfoBarGenerics] Key 'KEY_PREVIOUS' (412) Make.
11:42:10.3091 [eRCDeviceInputDev] 0 19c 1
11:42:10.3097 [InfoBarGenerics] Key 'KEY_PREVIOUS' (412) Break.
11:42:10.7361 [eRCDeviceInputDev] 1 b 1
11:42:10.7367 [InfoBarGenerics] Key 'KEY_0' (11) Make.
11:42:10.9412 [eRCDeviceInputDev] 0 b 1
11:42:10.9415 [InfoBarGenerics] Key 'KEY_0' (11) Break.
11:42:11.3453 [eRCDeviceInputDev] 1 197 1
11:42:11.3456 [InfoBarGenerics] Key 'KEY_NEXT' (407) Make.
11:42:11.5548 [eRCDeviceInputDev] 0 197 1
11:42:11.5553 [InfoBarGenerics] Key 'KEY_NEXT' (407) Break.
11:42:12.8887 [eRCDeviceInputDev] 1 8b 1
11:42:12.8894 [InfoBarGenerics] Key 'KEY_MENU' (139) Make.
11:42:13.0931 [eRCDeviceInputDev] 0 8b 1
11:42:13.0935 [InfoBarGenerics] Key 'KEY_MENU' (139) Break.
11:42:20.0088 [eRCDeviceInputDev] 1 166 1
11:42:20.0093 [InfoBarGenerics] Key 'KEY_INFO' (358) Make.
11:42:20.2132 [eRCDeviceInputDev] 0 166 1
11:42:20.2135 [InfoBarGenerics] Key 'KEY_INFO' (358) Break.
11:42:21.0186 [eRCDeviceInputDev] 1 67 1
11:42:21.0190 [InfoBarGenerics] Key 'KEY_UP' (103) Make.
11:42:21.2212 [eRCDeviceInputDev] 0 67 1
11:42:21.2215 [InfoBarGenerics] Key 'KEY_UP' (103) Break.
11:42:21.7552 [eRCDeviceInputDev] 1 69 1
11:42:21.7556 [InfoBarGenerics] Key 'KEY_LEFT' (105) Make.
11:42:21.9572 [eRCDeviceInputDev] 0 69 1
11:42:21.9576 [InfoBarGenerics] Key 'KEY_LEFT' (105) Break.
11:42:21.9580 [Screen] Showing screen 'UnhandledKey'.
11:42:22.9297 [eRCDeviceInputDev] 1 6a 1
11:42:22.9302 [InfoBarGenerics] Key 'KEY_RIGHT' (106) Make.
11:42:23.1332 [eRCDeviceInputDev] 0 6a 1
11:42:23.1336 [InfoBarGenerics] Key 'KEY_RIGHT' (106) Break.
11:42:23.1339 [Screen] Showing screen 'UnhandledKey'.
11:42:24.0009 [eRCDeviceInputDev] 1 6c 1
11:42:24.0014 [InfoBarGenerics] Key 'KEY_DOWN' (108) Make.
11:42:24.2052 [eRCDeviceInputDev] 0 6c 1
11:42:24.2057 [InfoBarGenerics] Key 'KEY_DOWN' (108) Break.
11:42:27.2268 [eRCDeviceInputDev] 1 ae 1
11:42:27.2274 [InfoBarGenerics] Key 'KEY_EXIT' (174) Make.
11:42:27.2280 [ActionMap] Map context 'HelpActions' -> Unknown action 'cancel'!  (Typo in map?)
11:42:27.4292 [eRCDeviceInputDev] 0 ae 1
11:42:27.4296 [InfoBarGenerics] Key 'KEY_EXIT' (174) Break.
11:42:27.4300 [ActionMap] Map context 'OkCancelActions' -> Action 'cancel'.
11:42:27.4311 [Screen] Showing screen '['HelpMenu_summary', 'SimpleSummary']'.
11:42:27.4327 [Screen] Showing screen 'HelpMenu'.
11:42:28.6852 [eRCDeviceInputDev] 1 16d 1
11:42:28.6858 [InfoBarGenerics] Key 'KEY_EPG' (365) Make.
11:42:28.8932 [eRCDeviceInputDev] 0 16d 1
11:42:28.8936 [InfoBarGenerics] Key 'KEY_EPG' (365) Break.
11:42:32.5294 [eRCDeviceInputDev] 1 73 1
11:42:32.5300 [InfoBarGenerics] Key 'KEY_VOLUMEUP' (115) Make.
11:42:32.5305 [ActionMap] Map context 'GlobalActions' -> Action 'volumeUp'.
11:42:32.7333 [eRCDeviceInputDev] 0 73 1
11:42:32.7343 [InfoBarGenerics] Key 'KEY_VOLUMEUP' (115) Break.
11:42:34.7963 [eRCDeviceInputDev] 1 9c 1
11:42:34.7969 [InfoBarGenerics] Key 'KEY_BOOKMARKS' (156) Make.
11:42:34.9971 [eRCDeviceInputDev] 0 9c 1
11:42:34.9977 [InfoBarGenerics] Key 'KEY_BOOKMARKS' (156) Break.
11:42:34.9981 [Screen] Showing screen 'UnhandledKey'.
11:42:35.5627 [eRCDeviceInputDev] 1 192 1
11:42:35.5633 [InfoBarGenerics] Key 'KEY_CHANNELUP' (402) Make.
11:42:35.7652 [eRCDeviceInputDev] 0 192 1
11:42:35.7658 [InfoBarGenerics] Key 'KEY_CHANNELUP' (402) Break.
11:42:35.7662 [ActionMap] Map context 'HelpMenuListboxActions' -> Action 'ignore'.
11:42:37.1736 [eRCDeviceInputDev] 1 72 1
11:42:37.1741 [InfoBarGenerics] Key 'KEY_VOLUMEDOWN' (114) Make.
11:42:37.1745 [ActionMap] Map context 'GlobalActions' -> Action 'volumeDown'.
11:42:37.1749 [eDVBVolumecontrol] Setvolume: raw: 90 90, -1db: 7 7
11:42:37.1751 [eDVBVolumecontrol] SetVolume failed to open mixer: Function not implemented
11:42:37.1756 [Screen] Showing screen 'Volume'.
11:42:37.1762 [Volume] Volume set to 90.
11:42:37.3813 [eRCDeviceInputDev] 0 72 1
11:42:37.3820 [InfoBarGenerics] Key 'KEY_VOLUMEDOWN' (114) Break.
11:42:38.9475 [eRCDeviceInputDev] 1 189 1
11:42:38.9483 [InfoBarGenerics] Key 'KEY_VIDEO' (393) Make.
11:42:39.1492 [eRCDeviceInputDev] 0 189 1
11:42:39.1497 [InfoBarGenerics] Key 'KEY_VIDEO' (393) Break.
11:42:39.1501 [Screen] Showing screen 'UnhandledKey'.
11:42:39.8339 [eRCDeviceInputDev] 1 193 1
11:42:39.8345 [InfoBarGenerics] Key 'KEY_CHANNELDOWN' (403) Make.
11:42:40.0372 [eRCDeviceInputDev] 0 193 1
11:42:40.0378 [InfoBarGenerics] Key 'KEY_CHANNELDOWN' (403) Break.
11:42:40.0382 [ActionMap] Map context 'HelpMenuListboxActions' -> Action 'ignore'.
11:42:41.4706 [eRCDeviceInputDev] 1 18e 1
11:42:41.4712 [InfoBarGenerics] Key 'KEY_RED' (398) Make.
11:42:41.6772 [eRCDeviceInputDev] 0 18e 1
11:42:41.6777 [InfoBarGenerics] Key 'KEY_RED' (398) Break.
11:42:42.1055 [eRCDeviceInputDev] 1 18f 1
11:42:42.1061 [InfoBarGenerics] Key 'KEY_GREEN' (399) Make.
11:42:42.4211 [eRCDeviceInputDev] 0 18f 1
11:42:42.4216 [InfoBarGenerics] Key 'KEY_GREEN' (399) Break.
11:42:42.4221 [Screen] Showing screen 'UnhandledKey'.
11:42:42.9891 [eRCDeviceInputDev] 1 190 1
11:42:42.9897 [InfoBarGenerics] Key 'KEY_YELLOW' (400) Make.
11:42:43.1972 [eRCDeviceInputDev] 0 190 1
11:42:43.1977 [InfoBarGenerics] Key 'KEY_YELLOW' (400) Break.
11:42:44.2129 [eRCDeviceInputDev] 1 191 1
11:42:44.2135 [InfoBarGenerics] Key 'KEY_BLUE' (401) Make.
11:42:44.4211 [eRCDeviceInputDev] 0 191 1
11:42:44.4216 [InfoBarGenerics] Key 'KEY_BLUE' (401) Break.
11:42:46.2182 [eRCDeviceInputDev] 1 a7 1
11:42:46.2189 [InfoBarGenerics] Key 'KEY_RECORD' (167) Make.
11:42:46.4211 [eRCDeviceInputDev] 0 a7 1
11:42:46.4216 [InfoBarGenerics] Key 'KEY_RECORD' (167) Break.
11:42:47.2576 [eRCDeviceInputDev] 1 80 1
11:42:47.2582 [InfoBarGenerics] Key 'KEY_STOP' (128) Make.
11:42:47.4612 [eRCDeviceInputDev] 0 80 1
11:42:47.4616 [InfoBarGenerics] Key 'KEY_STOP' (128) Break.
11:42:48.2741 [eRCDeviceInputDev] 1 a4 1
11:42:48.2747 [InfoBarGenerics] Key 'KEY_PLAYPAUSE' (164) Make.
11:42:48.4771 [eRCDeviceInputDev] 0 a4 1
11:42:48.4776 [InfoBarGenerics] Key 'KEY_PLAYPAUSE' (164) Break.
11:42:49.3330 [eRCDeviceInputDev] 1 16a 1
11:42:49.3336 [InfoBarGenerics] Key 'KEY_PROGRAM' (362) Make.
11:42:49.5411 [eRCDeviceInputDev] 0 16a 1
11:42:49.5416 [InfoBarGenerics] Key 'KEY_PROGRAM' (362) Break.
11:42:51.1456 [eRCDeviceInputDev] 1 a5 1
11:42:51.1462 [InfoBarGenerics] Key 'KEY_PREVIOUSSONG' (165) Make.
11:42:51.3492 [eRCDeviceInputDev] 0 a5 1
11:42:51.3497 [InfoBarGenerics] Key 'KEY_PREVIOUSSONG' (165) Break.
11:42:52.0299 [eRCDeviceInputDev] 1 a8 1
11:42:52.0305 [InfoBarGenerics] Key 'KEY_REWIND' (168) Make.
11:42:52.2372 [eRCDeviceInputDev] 0 a8 1
11:42:52.2376 [InfoBarGenerics] Key 'KEY_REWIND' (168) Break.
11:42:52.2380 [ActionMap] Map context 'HelpMenuListboxActions' -> Action 'ignore'.
11:42:52.9490 [eRCDeviceInputDev] 1 d0 1
11:42:52.9496 [InfoBarGenerics] Key 'KEY_FASTFORWARD' (208) Make.
11:42:53.1572 [eRCDeviceInputDev] 0 d0 1
11:42:53.1576 [InfoBarGenerics] Key 'KEY_FASTFORWARD' (208) Break.
11:42:53.1580 [ActionMap] Map context 'HelpMenuListboxActions' -> Action 'ignore'.
11:42:54.2393 [eRCDeviceInputDev] 1 a3 1
11:42:54.2399 [InfoBarGenerics] Key 'KEY_NEXTSONG' (163) Make.
11:42:54.4452 [eRCDeviceInputDev] 0 a3 1
11:42:54.4456 [InfoBarGenerics] Key 'KEY_NEXTSONG' (163) Break.
11:42:56.0931 [eRCDeviceInputDev] 1 160 1
11:42:56.0940 [InfoBarGenerics] Key 'KEY_OK' (352) Make.
11:42:56.0944 [ActionMap] Map context 'HelpActions' -> Action 'select'.
11:42:56.0958 [Screen] Showing screen 'InfoBarSummary'.
11:42:56.0999 [ActionMap] Map context 'InfobarCueSheetActions' -> Action 'jumpNextMark'.
11:42:56.3012 [eRCDeviceInputDev] 0 160 1
11:42:56.3017 [InfoBarGenerics] Key 'KEY_OK' (352) Break.

```

**Pull request merged**
